In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [4]:
Dataset=pd.read_csv('BankNote_Authentication.csv')

In [5]:
Dataset

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [6]:
X=Dataset.iloc[:,:-1].values
Y=Dataset.iloc[:,-1].values

In [8]:
Dataset.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=True)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
X_train

array([[-1.51401341,  0.08619198, -0.15761757,  0.03308202],
       [-2.25908255,  0.80838057, -0.15865873, -2.63958749],
       [ 0.61654128,  0.45647802, -1.53052454, -0.74985158],
       ...,
       [-1.7133756 ,  0.7213991 , -0.18402775, -2.05994996],
       [ 0.56409063,  0.01689634,  0.20526148,  0.51263232],
       [-0.98467732,  0.30238112, -0.49200411, -0.04352437]])

In [12]:
X_test

array([[-1.42370738, -0.00656267, -0.27760647, -0.61389076],
       [ 0.30300926,  0.45576291,  0.23375399,  0.66032257],
       [-1.58929803, -1.78697051,  2.69983652, -0.134372  ],
       ...,
       [-0.78705519,  0.14067966, -0.93744834, -0.51501451],
       [-1.13638293,  1.65184089,  0.29343294, -2.11371302],
       [-0.74458331,  0.2485911 , -0.74278188, -1.15090015]])

In [13]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()
model1.fit(X_train,Y_train)
logresult=model1.predict(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier(random_state=0)
model2.fit(X_train,Y_train)
randomResult=model2.predict(X_test)

In [15]:
logresult

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,

In [16]:
randomResult

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,

In [20]:
np.concatenate((Y_test.reshape(-1,1),logresult.reshape(-1,1),randomResult.reshape(-1,1)),1)

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,r2_score,classification_report
print(confusion_matrix(Y_test,logresult))

[[186   7]
 [  1 149]]


In [24]:
print(accuracy_score(Y_test,logresult))


0.9766763848396501


In [25]:
print(r2_score(Y_test,logresult))


0.9052158894645941


In [26]:
print(classification_report(Y_test,logresult))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98       193
           1       0.96      0.99      0.97       150

    accuracy                           0.98       343
   macro avg       0.97      0.98      0.98       343
weighted avg       0.98      0.98      0.98       343



In [27]:
print('Random Forest')
print(confusion_matrix(Y_test,randomResult))

Random Forest
[[192   1]
 [  0 150]]


In [28]:
print(accuracy_score(Y_test,randomResult))

0.9970845481049563


In [29]:
print(r2_score(Y_test,randomResult))

0.9881519861830743


In [30]:
print(classification_report(Y_test,randomResult))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       193
           1       0.99      1.00      1.00       150

    accuracy                           1.00       343
   macro avg       1.00      1.00      1.00       343
weighted avg       1.00      1.00      1.00       343

